version: '3'
services:
  bdev:
    container_name: bdev
    image: bdev
    build:
      context: ./backendDev
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  bprod:
    container_name: bprod
    image: bprod
    build:
      context: ./backendProd
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"